spring.application.name=flowtide-producer
server.port=8081

# Points to FlowTide broker's internal TCP registry
kafka.registry.host=localhost
kafka.registry.port=7070
kafka.producer.thread-pool-size=8

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,metrics
